# Generated by Django 5.2.15 on 2026-06-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0299_itemprogramtime_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBICSConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=190)),
                ('bank_name', models.CharField(max_length=190)),
                ('host_id', models.CharField(max_length=190)),
                ('partner_id', models.CharField(max_length=190)),
                ('user_id', models.CharField(max_length=190)),
                ('ebics_url', models.URLField()),
                ('ebics_version', models.CharField(default='H004', max_length=4)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('keys_created', models.BooleanField(default=False)),
                ('ini_sent', models.BooleanField(default=False)),
                ('hia_sent', models.BooleanField(default=False)),
                ('bank_keys_activated', models.BooleanField(default=False)),
                ('keyring_data', models.TextField(default='')),
                ('passphrase', models.CharField(default='', max_length=190)),
                ('last_imported_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebics_connections', to='pretixbase.organizer')),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
    ]
